In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, IntegerType, FloatType, StringType, StructField

# Create a SparkSession
spark = SparkSession.builder.appName("CSVReader").getOrCreate()

In [2]:
schema = StructType([
    StructField("Emp_Id", StringType(), False),
    StructField("Emp_Name", StringType(), False),
    StructField("Department", StringType(), False),
    StructField("Salary", IntegerType(), False),
    StructField("Phone", IntegerType(), True),
])

Filename : employee.csv

In [3]:
'''
emp_id, emp_name, dept, salary,phone
A101,jhon,computer science,1000,+1 (701) 846 958
A102,Peter,Electronics,2000,
A103,Micheal,IT,2500,
'''

SyntaxError: invalid syntax (<ipython-input-3-e5046cf8df66>, line 2)

Read the input file with user-defined schema.

In [3]:
# Create a dataframe on top a csv file
df = (spark.read
      .format("csv")
      .schema(schema)
      .option("header", "true")
      .load("employee.csv")
)
# Display he dataframe content
df.show()

+------+--------+----------------+------+----------+
|Emp_Id|Emp_Name|      Department|Salary|     Phone|
+------+--------+----------------+------+----------+
|  A101|    jhon|computer science|  1000|1701846958|
|  A102|   Peter|     Electronics|  2000|      NULL|
|  A103| Micheal|              IT|  2500|      NULL|
+------+--------+----------------+------+----------+

In [4]:
df.printSchema()

root
 |-- Emp_Id: string (nullable = true)
 |-- Emp_Name: string (nullable = true)
 |-- Department: string (nullable = true)
 |-- Salary: integer (nullable = true)
 |-- Phone: integer (nullable = true)